apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: db-deployment
  name: db-deployment
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      run: db-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: db-deployment
    spec:
      containers:
      - image: postgres:9.4
        name: db-deployment
        resources: {}
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
      volumes:
      - name: db-data
