apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: result-deployment
  name: result-deployment
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      run: result-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: result-deployment
    spec:
      containers:
      - image: kodekloud/examplevotingapp_result:before
        name: result-deployment
