apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: result-deployment
  name: result-service
  namespace: vote
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 80
    nodePort: 31001
  selector:
    run: result-deployment
  type: NodePort
