apiVersion: v1
kind: Service
metadata:
  labels:
    app: drupal
  name: drupal-service
spec:
  ports:
  - nodePort: 30095
    port: 30095
    protocol: TCP
    targetPort: 30095
  selector:
    app: drupal
  type: NodePort
status:
  loadBalancer: {}
